visible_variables: []
temporal_strategy: "mean_span"
spatial_bbox: [-90.0, -180.0, 90.0, 180.0]

# Execution and Engine Parameters
rendering_mode: "local"
headless: false
debug: false

# Domain selection properties (size is measured in kilometers)
domain_center_lon: 11.931428  # Radfeld, Tirol
domain_center_lat: 47.456408  # Radfeld, Tirol
domain_size_x_km: 0.5        # Domain width in kilometers
domain_size_y_km: 0.5        # Domain height in kilometers

parser_configs:
  default:
    spatial_stride: 1
    temporal_stride: 1
    max_domain_x: 300
    max_domain_y: 300
    max_domain_z: 50
  WRF:
    spatial_stride: 2
    temporal_stride: 1
    max_domain_x: 400
    max_domain_y: 400
    max_domain_z: 45
  UAS:
    spatial_stride: 1
    temporal_stride: 1
    max_domain_x: 5000
    max_domain_y: 5000
    max_domain_z: 100
